// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn7aal9upL5TX2CNFUMbhmtQ1QpPPjWqg',
    appId: '1:574938966496:web:f22d6040aa0fb41617a385',
    messagingSenderId: '574938966496',
    projectId: 'lab08-a3aba',
    authDomain: 'lab08-a3aba.firebaseapp.com',
    storageBucket: 'lab08-a3aba.appspot.com',
    measurementId: 'G-R0KBYTWV5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpPIYf5ecCpNlmRPAxAh_-LTQKgnamn7Q',
    appId: '1:574938966496:android:dd63da4a34cdceb617a385',
    messagingSenderId: '574938966496',
    projectId: 'lab08-a3aba',
    storageBucket: 'lab08-a3aba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXJlVDoRa50O9khBFFQsJbcGzzeP0D-14',
    appId: '1:574938966496:ios:6708849e728ca0a017a385',
    messagingSenderId: '574938966496',
    projectId: 'lab08-a3aba',
    storageBucket: 'lab08-a3aba.appspot.com',
    iosClientId: '574938966496-22nju8ee511hdeg9g2tvdtre4j3t6emm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXJlVDoRa50O9khBFFQsJbcGzzeP0D-14',
    appId: '1:574938966496:ios:6708849e728ca0a017a385',
    messagingSenderId: '574938966496',
    projectId: 'lab08-a3aba',
    storageBucket: 'lab08-a3aba.appspot.com',
    iosClientId: '574938966496-22nju8ee511hdeg9g2tvdtre4j3t6emm.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );
}
